trigger:
  - dev

jobs:
  - template: build-windows.yaml
    parameters:
      visualStudioVersion: 2019
  # Temporarily disabled, because of issue of compiling Eigen with VS2022.
  # - template: build-windows.yaml
  #   parameters:
  #     visualStudioVersion: 2022
